{% set name = "docxtpl" %}
{% set version = "0.19.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9cbacfe58ecf9eb481f28f60043c200f3e02205c0f41d710328e2558acbefba9

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - poetry-core
    - pip
  run:
    - python >=3.11.0,<4.0.0
    - python-docx >=1.1.2,<2.0.0
    - docxcompose >=1.4.0,<2.0.0
    - jinja2 >=3.1.4,<4.0.0
    - black >=24.4.2,<25.0.0
    - lxml

test:
  imports:
    - docxtpl
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/elapouya/python-docx-template
  license: LGPL-2.1-only
  license_family: LGPL
  license_file: LICENSE.txt
  summary: Python docx template engine
  description: |
    Use a MS Word docx document as a jinja2 template  
  doc_url: https://docxtpl.readthedocs.io/
  dev_url: https://github.com/elapouya/python-docx-template

extra:
  recipe-maintainers:
    - jfcorbett
    - YYYasin19
