{% set name = "docxtpl" %}
{% set version = "0.14.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 53633030099e48ee7086b367ddcafce515a9b61bfab7d9f322eb5f6f359bca79

build:
  number: 0
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '
  noarch: python

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - jinja2
    - lxml
    - python >=3.6
    - python-docx
    - six

test:
  imports:
    - docxtpl

about:
  home: https://github.com/elapouya/python-docx-template
  license: LGPL-2.1-only
  license_family: LGPL
  license_file: LICENSE.txt
  summary: Python docx template engine
  description: |
    Use a MS Word docx document as a jinja2 template  
  doc_url: https://docxtpl.readthedocs.io/
  dev_url: https://github.com/elapouya/python-docx-template

extra:
  recipe-maintainers:
    - jfcorbett
