{% set name = "docxtpl" %}
{% set version = "0.20.2" %}
{% set python_min = "3.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: eddf3350d70b4d123208e801d585bcb313d21044a377a14f75a66d0965841de1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >={{ python_min }}
    - poetry-core
    - poetry-dynamic-versioning >=1.0.0,<2.0.0
    - pip
  run:
    - python >={{ python_min }}
    - python-docx
    - jinja2
    - lxml

test:
  imports:
    - docxtpl
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/elapouya/python-docx-template
  license: LGPL-2.1-only
  license_family: LGPL
  license_file: LICENSE.txt
  summary: Python docx template engine
  description: |
    Use a MS Word docx document as a jinja2 template  
  doc_url: https://docxtpl.readthedocs.io/
  dev_url: https://github.com/elapouya/python-docx-template

extra:
  recipe-maintainers:
    - jfcorbett
    - YYYasin19
