{% set name = "docxtpl" %}
{% set version = "0.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 20af085d26fdad677c0122cd11a5d960ec3fc7ba221a80b4af447962acba3774

build:
  number: 1
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '
  noarch: python

requirements:
  host:
    - pip
    - python
  run:
    - jinja2
    - lxml
    - python
    - python-docx
    - six

test:
  imports:
    - docxtpl

about:
  home: https://github.com/elapouya/python-docx-template
  license: LGPL 2.1
  license_family: LGPL
  license_file: LICENSE.txt
  summary: Python docx template engine
  description: |
    Use a MS Word docx document as a jinja2 template  
  doc_url: https://docxtpl.readthedocs.io/
  dev_url: https://github.com/elapouya/python-docx-template

extra:
  recipe-maintainers:
    - jfcorbett
