schema_version: 1

context:
  version: "0.20.2"

package:
  name: docxtpl
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/d/docxtpl/docxtpl-${{ version }}.tar.gz
  sha256: eddf3350d70b4d123208e801d585bcb313d21044a377a14f75a66d0965841de1

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - poetry-core
    - poetry-dynamic-versioning >=1.0.0,<2.0.0
    - pip
  run:
    - python >=${{ python_min }}
    - python-docx
    - docxcompose
    - jinja2
    - lxml

tests:
  - python:
      imports:
        - docxtpl
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  license: LGPL-2.1-only
  license_file: LICENSE.txt
  summary: Python docx template engine
  description: |
    Use a MS Word docx document as a jinja2 template
  homepage: https://github.com/elapouya/python-docx-template
  repository: https://github.com/elapouya/python-docx-template
  documentation: https://docxtpl.readthedocs.io/

extra:
  recipe-maintainers:
    - jfcorbett
    - YYYasin19
    - mgorny
